import { Urbanist } from "next/font/google";
import Navbar from "@/components/ui/navbar";
import "./globals.css";
import Footer from "@/components/ui/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const UrbanistFont = Urbanist({
  variable: "--font-urbanist",
  display: "swap",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${UrbanistFont.className} selection:bg-secondary selection:text-white`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
